spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1175341729/spring-cloud-config.git
          search-paths: spring-cloud-config
      label: master
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
